name: Push Docker Image

on:
  push:
    branches:
      - master
  # Trigger rebuild in case of new runner version
  schedule:
    - cron: "1 1 1 * *"

env:
  RUNNER_VERSION: ""

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Get the latest runner version
        run: |
          RUNNER_VERSION=$(curl -s https://github.com/actions/runner/releases/latest/ -i | sed -En 's#^location: https://github.com/actions/runner/releases/tag/v(.*)#\1#p' | sed 's/\r$//')
          echo "RUNNER_VERSION=$RUNNER_VERSION" | tee $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: koyeb/github-runner:latest
          build-args: |
            RUNNER_VERSION=${{ env.RUNNER_VERSION }}
